#Mad Lib
holiday = input ("Whats a holiday? ")
verb = input ("What's a verb with ing? >_ ")
fruit = input ("What's a fruit? >_")
person = input ("What's a persons name? >_")
thing = input ("What's a thing? >_")
thing2 = input ("What's another thing? >_")
feeling = input ("Name a feeling. >_")
food = input ("List a food item. >_")
drink = input ("list a drink item. >_")
verb2 = input ("List another verb. >_")
person2 = input ("List another person. >_")
thing3 = input ("List another thing >_")

print("We are so excited it's %s!" % holiday)
print("After we %s %s with my friend," % (verb, fruit))
print ("%s, we're going on a %s ride and through a %s Maze" % (person, thing, thing2))
print ("We're going to be %s after, so dinner is next!" % feeling)
print ("We are going to eat %s and wash it down with %s." % (food, drink))
print ("Late at night, we plan to %s down a scary street." % verb2)
print ("%s says it's haunted! But we wont be scared since we have a %s. Happy Holloween!" % (person2, thing3))